# Generated by Django 6.0.5 on 2026-05-07 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='semester',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('semester', 'subject_name')},
        ),
    ]
