# Generated by Django 6.0.5 on 2026-05-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('semester__semester_name', 'subject__subject_name', 'id'), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('semester_name',), 'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('semester__semester_name', 'subject_name'), 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
