# Generated by Django 6.0.5 on 2026-05-11 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_alter_question_options_alter_semester_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=None,
        ),
        migrations.AddField(
            model_name="question",
            name="subject_name",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.RemoveField(
            model_name="question",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="question",
            name="subject",
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ("subject_name", "id")},
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_questions", models.PositiveIntegerField()),
                ("correct_answers", models.PositiveIntegerField()),
                ("wrong_answers", models.PositiveIntegerField()),
                ("final_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("submitted_answers", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exams.testuser",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.DeleteModel(
            name="Semester",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
