# Generated by Django 6.0.4 on 2026-05-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_testuser_remove_question_semester_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
                "ordering": ("semester_name",),
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ("semester__semester_name", "subject__subject_name", "id"),
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="subject_name",
        ),
        migrations.AddField(
            model_name="question",
            name="semester",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exams.semester",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=150)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="exams.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ("semester__semester_name", "subject_name"),
                "unique_together": {("semester", "subject_name")},
            },
        ),
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exams.subject",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TestResult",
        ),
        migrations.DeleteModel(
            name="TestUser",
        ),
    ]
