# Generated by Django 6.0.4 on 2026-05-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.IntegerField(default=1),
        ),
    ]
